#!/bin/sh
option_file=/tmp/xl2tpd.options
config_file=/tmp/xl2tpd.conf
g_l2tp_tunnel=

start () {
    if [ ! -d /var/run/xl2tpd ]; then
        mkdir -p /var/run/xl2tpd
    fi

    build_config_file
    xl2tpd -c $config_file
    echo "c $g_l2tp_tunnel" > /var/run/xl2tpd/l2tp-control
    return
}

stop () {
    killall -9 xl2tpd
}

restart () {
    stop
    start
}

build_config_file () {
    g_target=$config_file
    > $config_file
    g_append [global]
    g_append port 1701
    g_append access control = no
    g_append rand source = dev
    g_append $newline
    g_append [lac l2tpd]
    g_append pppoptfile = $option_file
    g_append lns = $(nvram get wan0_l2tp_lns)
    g_append name = default
    g_append require authentication = no
    g_append tunnel rws = 8
    g_append autodial = yes
    g_append redial = yes
    g_append redial timeout = 15
    g_append tx bps = 100000000
    g_append rx bps = 100000000

    g_target=$option_file
    > $option_file
    g_append noauth
    g_append user $(nvram get wan0_l2tp_username)
    g_append password $(nvram get wan0_l2tp_password)
    g_append refuse-eap
    g_append mtu 1450
    g_append mru 1450
    g_append maxfail 0
    g_append holdoff 10
    g_append ipcp-accept-remote ipcp-accept-local
    g_append noipdefault
    g_append usepeerdns
    g_append default-asyncmap
    g_append nopcomp noaccomp
    g_append novj nobsdcomp nodeflate
    g_append lcp-max-terminate 0
    g_append lcp-echo-interval 20
    g_append lcp-echo-failure 6
    g_append unit 5
    g_append ktune
}

g_append () {
    if [ -z "$g_target" ]; then return; fi
    echo "$*" >> $g_target
}
